"""add file metadata to evidence

Revision ID: 8662414cfeb7
Revises: bf1b27262659
Create Date: 2026-03-03 15:26:47.331081
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '8662414cfeb7'
down_revision: Union[str, None] = 'bf1b27262659'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evidence', sa.Column('file_name', sa.String(length=256), nullable=True))
    op.add_column('evidence', sa.Column('file_size', sa.BigInteger(), nullable=True))
    op.add_column('evidence', sa.Column('mime_type', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('evidence', 'mime_type')
    op.drop_column('evidence', 'file_size')
    op.drop_column('evidence', 'file_name')
    # ### end Alembic commands ###
