"""add all phase2 models

Revision ID: eb9e54c16bdd
Revises: 
Create Date: 2026-03-03 09:04:40.776033
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'eb9e54c16bdd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cmmc_domains',
    sa.Column('domain_id', sa.String(length=4), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('creator_id', sa.String(length=128), server_default='system', nullable=False),
    sa.Column('row_version', sa.Integer(), server_default='1', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain_id')
    )
    op.create_table('cmmc_levels',
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('assessment_type', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('creator_id', sa.String(length=128), server_default='system', nullable=False),
    sa.Column('row_version', sa.Integer(), server_default='1', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('level')
    )
    op.create_table('organizations',
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('cage_code', sa.String(length=8), nullable=True),
    sa.Column('duns_number', sa.String(length=16), nullable=True),
    sa.Column('target_level', sa.Integer(), nullable=True),
    sa.Column('datapact_api_url', sa.String(length=512), nullable=True),
    sa.Column('datapact_api_key', sa.String(length=512), nullable=True),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('creator_id', sa.String(length=128), server_default='system', nullable=False),
    sa.Column('row_version', sa.Integer(), server_default='1', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('creator_id', sa.String(length=128), server_default='system', nullable=False),
    sa.Column('row_version', sa.Integer(), server_default='1', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('cmmc_practices',
    sa.Column('practice_id', sa.String(length=32), nullable=False),
    sa.Column('domain_ref', sa.String(length=4), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('assessment_objectives', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('evidence_requirements', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('nist_refs', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('creator_id', sa.String(length=128), server_default='system', nullable=False),
    sa.Column('row_version', sa.Integer(), server_default='1', nullable=False),
    sa.ForeignKeyConstraint(['domain_ref'], ['cmmc_domains.domain_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('practice_id')
    )
    op.create_table('users',
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('password_hash', sa.String(length=512), nullable=False),
    sa.Column('org_id', sa.String(length=64), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('creator_id', sa.String(length=128), server_default='system', nullable=False),
    sa.Column('row_version', sa.Integer(), server_default='1', nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('assessments',
    sa.Column('org_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('target_level', sa.Integer(), nullable=False),
    sa.Column('assessment_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('lead_assessor_id', sa.String(length=64), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('overall_score', sa.Float(), nullable=True),
    sa.Column('sprs_score', sa.Integer(), nullable=True),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('creator_id', sa.String(length=128), server_default='system', nullable=False),
    sa.Column('row_version', sa.Integer(), server_default='1', nullable=False),
    sa.ForeignKeyConstraint(['lead_assessor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_log',
    sa.Column('user_id', sa.String(length=64), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('resource_type', sa.String(length=64), nullable=False),
    sa.Column('resource_id', sa.String(length=64), nullable=True),
    sa.Column('details', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('creator_id', sa.String(length=128), server_default='system', nullable=False),
    sa.Column('row_version', sa.Integer(), server_default='1', nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('datapact_practice_mappings',
    sa.Column('org_id', sa.String(length=64), nullable=False),
    sa.Column('practice_id', sa.String(length=32), nullable=False),
    sa.Column('datapact_contract_id', sa.String(length=128), nullable=False),
    sa.Column('datapact_contract_name', sa.String(length=256), nullable=True),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('creator_id', sa.String(length=128), server_default='system', nullable=False),
    sa.Column('row_version', sa.Integer(), server_default='1', nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['practice_id'], ['cmmc_practices.practice_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_roles',
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('role_id', sa.String(length=64), nullable=False),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('creator_id', sa.String(length=128), server_default='system', nullable=False),
    sa.Column('row_version', sa.Integer(), server_default='1', nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assessment_practices',
    sa.Column('assessment_id', sa.String(length=64), nullable=False),
    sa.Column('practice_id', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('assessor_notes', sa.Text(), nullable=True),
    sa.Column('datapact_sync_status', sa.String(length=32), nullable=True),
    sa.Column('datapact_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('creator_id', sa.String(length=128), server_default='system', nullable=False),
    sa.Column('row_version', sa.Integer(), server_default='1', nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ),
    sa.ForeignKeyConstraint(['practice_id'], ['cmmc_practices.practice_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('datapact_sync_logs',
    sa.Column('org_id', sa.String(length=64), nullable=False),
    sa.Column('assessment_id', sa.String(length=64), nullable=True),
    sa.Column('practice_id', sa.String(length=32), nullable=True),
    sa.Column('request_payload', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('response_payload', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('creator_id', sa.String(length=128), server_default='system', nullable=False),
    sa.Column('row_version', sa.Integer(), server_default='1', nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('findings',
    sa.Column('assessment_id', sa.String(length=64), nullable=False),
    sa.Column('practice_id', sa.String(length=32), nullable=True),
    sa.Column('finding_type', sa.String(length=32), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('creator_id', sa.String(length=128), server_default='system', nullable=False),
    sa.Column('row_version', sa.Integer(), server_default='1', nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('poams',
    sa.Column('org_id', sa.String(length=64), nullable=False),
    sa.Column('assessment_id', sa.String(length=64), nullable=True),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('creator_id', sa.String(length=128), server_default='system', nullable=False),
    sa.Column('row_version', sa.Integer(), server_default='1', nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evidence',
    sa.Column('assessment_practice_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('file_path', sa.String(length=512), nullable=True),
    sa.Column('file_url', sa.String(length=512), nullable=True),
    sa.Column('review_status', sa.String(length=32), nullable=False),
    sa.Column('reviewer_id', sa.String(length=64), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('creator_id', sa.String(length=128), server_default='system', nullable=False),
    sa.Column('row_version', sa.Integer(), server_default='1', nullable=False),
    sa.ForeignKeyConstraint(['assessment_practice_id'], ['assessment_practices.id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('poam_items',
    sa.Column('poam_id', sa.String(length=64), nullable=False),
    sa.Column('finding_id', sa.String(length=64), nullable=True),
    sa.Column('practice_id', sa.String(length=32), nullable=True),
    sa.Column('milestone', sa.String(length=256), nullable=True),
    sa.Column('scheduled_completion', sa.Date(), nullable=True),
    sa.Column('actual_completion', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('resources_required', sa.Text(), nullable=True),
    sa.Column('risk_accepted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('creator_id', sa.String(length=128), server_default='system', nullable=False),
    sa.Column('row_version', sa.Integer(), server_default='1', nullable=False),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], ),
    sa.ForeignKeyConstraint(['poam_id'], ['poams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('poam_items')
    op.drop_table('evidence')
    op.drop_table('poams')
    op.drop_table('findings')
    op.drop_table('datapact_sync_logs')
    op.drop_table('assessment_practices')
    op.drop_table('user_roles')
    op.drop_table('datapact_practice_mappings')
    op.drop_table('audit_log')
    op.drop_table('assessments')
    op.drop_table('users')
    op.drop_table('cmmc_practices')
    op.drop_table('roles')
    op.drop_table('organizations')
    op.drop_table('cmmc_levels')
    op.drop_table('cmmc_domains')
    # ### end Alembic commands ###
